/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'
import { Route as DecksDeckIdIndexRouteImport } from './routes/decks.$deckId.index'
import { Route as DecksDeckIdReviewRouteImport } from './routes/decks.$deckId.review'
import { Route as DecksDeckIdReviewIndexRouteImport } from './routes/decks.$deckId.review.index'
import { Route as DecksDeckIdReviewFreeRouteImport } from './routes/decks.$deckId.review.free'
import { Route as DecksDeckIdCardsNewRouteImport } from './routes/decks.$deckId.cards.new'
import { Route as DecksDeckIdCardsGenerateRouteImport } from './routes/decks.$deckId.cards.generate'
import { Route as DecksDeckIdCardsCardIdEditRouteImport } from './routes/decks.$deckId.cards.$cardId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdIndexRoute = DecksDeckIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdReviewRoute = DecksDeckIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdReviewIndexRoute = DecksDeckIdReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksDeckIdReviewRoute,
} as any)
const DecksDeckIdReviewFreeRoute = DecksDeckIdReviewFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => DecksDeckIdReviewRoute,
} as any)
const DecksDeckIdCardsNewRoute = DecksDeckIdCardsNewRouteImport.update({
  id: '/cards/new',
  path: '/cards/new',
  getParentRoute: () => DecksDeckIdRoute,
} as any)
const DecksDeckIdCardsGenerateRoute =
  DecksDeckIdCardsGenerateRouteImport.update({
    id: '/cards/generate',
    path: '/cards/generate',
    getParentRoute: () => DecksDeckIdRoute,
  } as any)
const DecksDeckIdCardsCardIdEditRoute =
  DecksDeckIdCardsCardIdEditRouteImport.update({
    id: '/cards/$cardId/edit',
    path: '/cards/$cardId/edit',
    getParentRoute: () => DecksDeckIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/decks/$deckId/review': typeof DecksDeckIdReviewRouteWithChildren
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
  '/decks/$deckId/cards/generate': typeof DecksDeckIdCardsGenerateRoute
  '/decks/$deckId/cards/new': typeof DecksDeckIdCardsNewRoute
  '/decks/$deckId/review/free': typeof DecksDeckIdReviewFreeRoute
  '/decks/$deckId/review/': typeof DecksDeckIdReviewIndexRoute
  '/decks/$deckId/cards/$cardId/edit': typeof DecksDeckIdCardsCardIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/decks/$deckId': typeof DecksDeckIdIndexRoute
  '/decks/$deckId/cards/generate': typeof DecksDeckIdCardsGenerateRoute
  '/decks/$deckId/cards/new': typeof DecksDeckIdCardsNewRoute
  '/decks/$deckId/review/free': typeof DecksDeckIdReviewFreeRoute
  '/decks/$deckId/review': typeof DecksDeckIdReviewIndexRoute
  '/decks/$deckId/cards/$cardId/edit': typeof DecksDeckIdCardsCardIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/decks/$deckId': typeof DecksDeckIdRouteWithChildren
  '/decks/$deckId/review': typeof DecksDeckIdReviewRouteWithChildren
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
  '/decks/$deckId/cards/generate': typeof DecksDeckIdCardsGenerateRoute
  '/decks/$deckId/cards/new': typeof DecksDeckIdCardsNewRoute
  '/decks/$deckId/review/free': typeof DecksDeckIdReviewFreeRoute
  '/decks/$deckId/review/': typeof DecksDeckIdReviewIndexRoute
  '/decks/$deckId/cards/$cardId/edit': typeof DecksDeckIdCardsCardIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/decks/$deckId'
    | '/decks/$deckId/review'
    | '/decks/$deckId/'
    | '/decks/$deckId/cards/generate'
    | '/decks/$deckId/cards/new'
    | '/decks/$deckId/review/free'
    | '/decks/$deckId/review/'
    | '/decks/$deckId/cards/$cardId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/decks/$deckId'
    | '/decks/$deckId/cards/generate'
    | '/decks/$deckId/cards/new'
    | '/decks/$deckId/review/free'
    | '/decks/$deckId/review'
    | '/decks/$deckId/cards/$cardId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/decks/$deckId'
    | '/decks/$deckId/review'
    | '/decks/$deckId/'
    | '/decks/$deckId/cards/generate'
    | '/decks/$deckId/cards/new'
    | '/decks/$deckId/review/free'
    | '/decks/$deckId/review/'
    | '/decks/$deckId/cards/$cardId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DecksDeckIdRoute: typeof DecksDeckIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/': {
      id: '/decks/$deckId/'
      path: '/'
      fullPath: '/decks/$deckId/'
      preLoaderRoute: typeof DecksDeckIdIndexRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/review': {
      id: '/decks/$deckId/review'
      path: '/review'
      fullPath: '/decks/$deckId/review'
      preLoaderRoute: typeof DecksDeckIdReviewRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/review/': {
      id: '/decks/$deckId/review/'
      path: '/'
      fullPath: '/decks/$deckId/review/'
      preLoaderRoute: typeof DecksDeckIdReviewIndexRouteImport
      parentRoute: typeof DecksDeckIdReviewRoute
    }
    '/decks/$deckId/review/free': {
      id: '/decks/$deckId/review/free'
      path: '/free'
      fullPath: '/decks/$deckId/review/free'
      preLoaderRoute: typeof DecksDeckIdReviewFreeRouteImport
      parentRoute: typeof DecksDeckIdReviewRoute
    }
    '/decks/$deckId/cards/new': {
      id: '/decks/$deckId/cards/new'
      path: '/cards/new'
      fullPath: '/decks/$deckId/cards/new'
      preLoaderRoute: typeof DecksDeckIdCardsNewRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/cards/generate': {
      id: '/decks/$deckId/cards/generate'
      path: '/cards/generate'
      fullPath: '/decks/$deckId/cards/generate'
      preLoaderRoute: typeof DecksDeckIdCardsGenerateRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
    '/decks/$deckId/cards/$cardId/edit': {
      id: '/decks/$deckId/cards/$cardId/edit'
      path: '/cards/$cardId/edit'
      fullPath: '/decks/$deckId/cards/$cardId/edit'
      preLoaderRoute: typeof DecksDeckIdCardsCardIdEditRouteImport
      parentRoute: typeof DecksDeckIdRoute
    }
  }
}

interface DecksDeckIdReviewRouteChildren {
  DecksDeckIdReviewFreeRoute: typeof DecksDeckIdReviewFreeRoute
  DecksDeckIdReviewIndexRoute: typeof DecksDeckIdReviewIndexRoute
}

const DecksDeckIdReviewRouteChildren: DecksDeckIdReviewRouteChildren = {
  DecksDeckIdReviewFreeRoute: DecksDeckIdReviewFreeRoute,
  DecksDeckIdReviewIndexRoute: DecksDeckIdReviewIndexRoute,
}

const DecksDeckIdReviewRouteWithChildren =
  DecksDeckIdReviewRoute._addFileChildren(DecksDeckIdReviewRouteChildren)

interface DecksDeckIdRouteChildren {
  DecksDeckIdReviewRoute: typeof DecksDeckIdReviewRouteWithChildren
  DecksDeckIdIndexRoute: typeof DecksDeckIdIndexRoute
  DecksDeckIdCardsGenerateRoute: typeof DecksDeckIdCardsGenerateRoute
  DecksDeckIdCardsNewRoute: typeof DecksDeckIdCardsNewRoute
  DecksDeckIdCardsCardIdEditRoute: typeof DecksDeckIdCardsCardIdEditRoute
}

const DecksDeckIdRouteChildren: DecksDeckIdRouteChildren = {
  DecksDeckIdReviewRoute: DecksDeckIdReviewRouteWithChildren,
  DecksDeckIdIndexRoute: DecksDeckIdIndexRoute,
  DecksDeckIdCardsGenerateRoute: DecksDeckIdCardsGenerateRoute,
  DecksDeckIdCardsNewRoute: DecksDeckIdCardsNewRoute,
  DecksDeckIdCardsCardIdEditRoute: DecksDeckIdCardsCardIdEditRoute,
}

const DecksDeckIdRouteWithChildren = DecksDeckIdRoute._addFileChildren(
  DecksDeckIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DecksDeckIdRoute: DecksDeckIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
